(deftheme StelsDevs
  "Created 2019-04-27.")

(custom-theme-set-variables
 'StelsDevs
 '(powerline-display-hud t))

(custom-theme-set-faces
 'StelsDevs
 '(cursor ((t (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:inherit bold :foreground "#D6BB9A"))))
 '(highlight ((t (:background "#303538"))))
 '(region ((t (:background "#C7AF3F" :foreground "#4E653D"))))
 '(shadow ((t (:foreground "#686868"))))
 '(secondary-selection ((t (:background "#100a14"))))
 '(trailing-whitespace ((t (:background "#FFFFFF" :foreground "black"))))
 '(font-lock-builtin-face ((t (:foreground "#9FB3C2"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#4F5A63"))))
 '(font-lock-constant-face ((t (:foreground "#D6BB9A"))))
 '(font-lock-doc-face ((t (:foreground "#4F5A63"))))
 '(font-lock-function-name-face ((t (:foreground "#9FB3C2"))))
 '(font-lock-keyword-face ((t (:foreground "#FAFFDB"))))
 '(font-lock-negation-char-face ((t (:foreground "#a45bad"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FAFFDB"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#D6BB9A"))))
 '(font-lock-type-face ((t (:foreground "#D6BB9A"))))
 '(font-lock-variable-name-face ((t (:foreground "#EEFFE3"))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" :underline (:color "#C7AF3F" :style wave)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#2aa1ae"))))
 '(link-visited ((t (:underline (:color foreground-color :style line) :foreground "#c56ec3"))))
 '(fringe ((t (:foreground "#b2b2b2" :background "#292b2e"))))
 '(header-line ((t (:background "#0a0814"))))
 '(tooltip ((t (:weight normal :slant normal :underline nil :foreground "#b2b2b2" :background "#5e5079"))))
 '(mode-line ((t (:box (:line-width 1 :color "#222226") :foreground "#b2b2b2" :background "#222226"))))
 '(mode-line-buffer-id ((t (:foreground "#D6BB9A" :inherit bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "#292b2e" :foreground "#b2b2b2"))))
 '(isearch ((t (:background "#FFE792" :foreground "#333333"))))
 '(isearch-fail ((t (:background "#FF5370" :foreground "#ffffff"))))
 '(lazy-highlight ((t (:weight normal :background "#29422d"))))
 '(match ((t (:foreground "#86dc2f" :background "#444155"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(buffer-menu-buffer ((t (:weight bold))))
 '(spaceline-flycheck-warning ((t (:distant-foreground "#968B26" :foreground "#F3EA98"))))
 '(powerline-active0 ((t (:inherit (mode-line)))))
 '(powerline-active1 ((t (:inherit (mode-line) :foreground "white" :background "grey17"))))
 '(powerline-active2 ((t (:inherit (mode-line) :foreground "white" :background "grey40"))))
 '(powerline-inactive0 ((t (:inherit (mode-line-inactive)))))
 '(powerline-inactive1 ((t (:inherit (mode-line-inactive) :background "grey11"))))
 '(powerline-inactive2 ((t (:inherit (mode-line-inactive) :background "grey20"))))
 '(error ((t (:foreground "#E02835" :weight bold))))
 '(default ((t (:inherit nil :stipple nil :background "#292D30" :foreground "#b2b2b2" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 115 :width normal :foundry "CTDB" :family "Fira Code"))))
 '(git-gutter+-added ((t (:weight bold :foreground "green"))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit (rainbow-delimiters-unmatched-face rainbow-delimiters-base-face))))))

(provide-theme 'StelsDevs)
